In [1]:
import numpy as np

In [2]:
s = 5

In [5]:
v = np.array([5,2,3])
m = np.array([[5,12,6],[-3,8,14]])

In [8]:
v.shape

(3,)

In [9]:
v.reshape(3,1)

array([[5],
       [2],
       [3]])

In [10]:
m.shape

(2, 3)

In [11]:
hung = np.array([[9,3,4],[5,6,7]])

In [12]:
hung.shape

(2, 3)

In [13]:
m - hung

array([[-4,  9,  2],
       [-8,  2,  7]])

In [14]:
hung + 1

array([[10,  4,  5],
       [ 6,  7,  8]])

In [16]:
hung

array([[9, 3, 4],
       [5, 6, 7]])

In [17]:
hung.T

array([[9, 5],
       [3, 6],
       [4, 7]])

In [18]:
x = np.array([5,6,7])
y = np.array([4,5,6])

In [19]:
np.dot(x,y)

92

In [20]:
np.dot(5,6)

30

In [21]:
np.dot(x,5)

array([25, 30, 35])

In [22]:
x * 5

array([25, 30, 35])

In [2]:
import pandas as pd

In [3]:
hung = pd.Series([10,20,30,40,50])

In [4]:
hung

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [5]:
hung.dtype

dtype('int64')

In [6]:
hung.size

5

In [7]:
hhung = pd.Series(['A','B','C','D'])

In [8]:
hhung.dtype

dtype('O')

In [9]:
hhung

0    A
1    B
2    C
3    D
dtype: object

In [12]:
hhung.name = 'hung'

In [13]:
hhung.size

4

In [16]:
hhung
import numpy as np

In [22]:
dung = [1,3,2,4]
dung1 = np.array(dung)
hung1 = pd.Series(dung)
hung2 = np.array(dung)
hung1.name = 'hung'

In [21]:
hung1,hung2

(0    1
 1    3
 2    2
 3    4
 Name: hung, dtype: int64,
 array([1, 3, 2, 4]))

In [23]:
hung2 = np.array(dung1)

In [24]:
hung2

array([1, 3, 2, 4])